server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oliy_mahad
    username: postgres
    password: 1
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 378604534320101
            clientSecret: 70861a4e9cb50df0faca8c07af5621b0
            accessTokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userAuthorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            resource:
              userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email
            scope:
              - email
              - public_profile

          google:
            clientId: 517447956930-ks6o0nu247mmb6pe9ag6gl2533443hvf.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
