server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oliy_mahad_course_db
    username: postgres
    password: 8
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
#          facebook:
#            client-id:
#            client-secret:
#            scope:
#              - email
#              - public_profile
          google:
            client-id: 517447956930-ks6o0nu247mmb6pe9ag6gl2533443hvf.apps.googleusercontent.com
            client-secret: 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
#            scope:
#              - email
#              - profile
  application:
    name: USER-SERVICE

