server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgres://localhost:5432/oliy_mahad_db
    username: postgres
    password: 8
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    #show-sql: true
    properties:
      hibernate.format_sql: true

  security:
    oauth2:
      client:
        registration:
#          facebook:
#            client-id:
#            client-secret:
#            scope:
#              - email
#              - public_profile
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
